window.EMPTY_CV_DATA = {
  "publishUrl": "",
  "publishStatus": "",
  "settings": {
    "webBackground": "bg01",
    "color": "gre",
    "dateFormat": "dd/mm/yyyy",
    "pageFormat": "a4",
    "addressFormat": {
      "order": [
        [
          "name",
        ],
        [
          "address",
        ],
        [
          "city",
          "postal",
        ],
        [
          "country",
        ],
      ],
      "delimiter": " ",
    },
    "name": "My CV",
    "fontFace": "rob-rob",
    "fontSize": "fs-1-4",
    "format": 20,
    "template": "basic",
    "lineHeight": "lh-1-1",
    "downloadCv": 0,
  },
  "thumbnailUrl": "",
  "isPublished": "",
  "isBeingProofread": false,
  "general": {
    "birthKey": "Date of birth",
    "street": "",
    "phoneValue": "",
    "descriptionKey": "Profile",
    "emailKey": "Email address",
    "nationalityKey": "Nationality",
    "firstNameKey": "First name",
    "websiteKey": "Web",
    "postal": "",
    "city": "",
    "addressKey": "Address",
    "name": "Personal info",
    "birthDate": "",
    "frontTitle": "",
    "lastNameValue": "",
    "backTitle": "",
    "phoneKey": "Phone number",
    "emailValue": "",
    "firstNameValue": "",
    "websiteValue": "",
    "country": "",
    "avatarShown": false,
    "icon": "ion-person",
    "nationality": "",
    "description": "",
    "lastNameKey": "Last name",
  },
  "publishTemplate": "paper",
  "isCover": false,
  "creationDate": "",
  "lastEditDate": "",
  "sections": [
    {
      "name": "Work experience",
      "data": {
        "entries": [
          {
            "endDate": [
              "",
              "",
            ],
            "city": "",
            "startDate": [
              "",
              "",
            ],
            "presentValue": "present",
            "country": "",
            "current": false,
            "jobTitle": "",
            "uuid": "bfe5fd45-c58d-4797-8bd7-b87107ba51a2",
            "description": "",
            "company": "",
          },
        ],
        "type": "work",
      },
      "type": "experience",
      "icon": "ion-briefcase",
      "uuid": "796cb788-9b44-42f9-b8c2-726816d3dc62",
    },
    {
      "name": "Education",
      "data": {
        "entries": [
          {
            "endDate": [
              "",
              "",
            ],
            "city": "",
            "startDate": [
              "",
              "",
            ],
            "presentValue": "present",
            "country": "",
            "current": false,
            "jobTitle": "",
            "uuid": "65e97593-0e77-45c2-a40f-00602adce144",
            "description": "",
            "company": "",
          },
        ],
        "type": "education",
      },
      "type": "experience",
      "icon": "ion-university",
      "uuid": "7278c661-92c8-4a97-9f1f-b26732ae5228",
    },
    {
      "name": "Skills",
      "data": [
        {
          "skills": [
            {
              "name": "",
              "description": "",
              "shown": "level",
              "skillLevel": 0,
            },
          ],
          "name": "",
        },
      ],
      "type": "skill",
      "icon": "ion-erlenmeyer-flask",
      "uuid": "efc196e7-003c-4683-83eb-afd54fe1804a",
    },
  ],
  "isProofread": "",
  "isWebsite": false,
  "avatarUrl": "",
  "isResume": true,
  "id": "",
};
